# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!


target 'IOS8SwiftCocoapodsTutorial' do
pod 'FontBlaster', '4.0.0'
end

target 'IOS8SwiftCocoapodsTutorialTests' do

end

